name: package_rename
description: "A Blazingly Fast way to configure your awesome flutter project to be production ready."
version: 1.10.0
homepage: https://outdatedguy.rocks
repository: https://github.com/OutdatedGuy/package_rename
topics:
  - rename
  - project-configuration
  - configuration-updater
  - package-rename
funding:
  - https://buymeacoffee.com/outdatedguy
  - https://github.com/sponsors/OutdatedGuy

environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  args: ^2.4.0
  html: ^0.15.0
  logger: ^2.0.1
  yaml: ^3.1.1

dev_dependencies:
  lints: ^6.0.0
