name: package_rename
description: A Blazingly Fast way to configure your awesome flutter project to be production ready.
version: 1.0.0
homepage: https://outdatedguy.rocks

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  html: ^0.15.0
  logger: ^1.1.0
  universal_io: ^2.0.4
  yaml: ^3.1.1

dev_dependencies:
  test: ^1.16.0
  very_good_analysis: ^3.0.1
